### PR TITLE
Make axios requests blocking

### PR DESCRIPTION
**Pull request by FFdhorkin**
I was  unable to get `cypress-testrail-reporter` working without the changes in this PR. I believe the root cause is this issue: https://github.com/cypress-io/cypress/issues/7139

What I was seeing: TestRail would open a report, but it would not mark test status or close the report. I figured out the problem was that the report ID was never coming back (the link to the testrail report that was generated had `unknown` for the run id)

My solution is to use the `deasync` library to block until TestRail responds. This feels a bit hacky to me, but nothing else I tried worked.

This seems to solve the issue for me. I have no idea how this library ever worked before - perhaps it works fine if your test run takes a while, but if it exits quickly, you run into the above cypress issue?

While I was at it, I put 4 other small things in this PR:
- Add missing glob dependency
- Add CYPRESS_TESTRAIL_REPORTER_USERNAME
- fix it saying "https://https://..." for report path
- filter caseIds before submitting to TestRail (if you had a test case with C## in the name, but C## wasn't a testrail case, you ended up getting a 400 error)

### CODE REVIEW

**Comment by mickosav** [comment]
@FFdhorkin I agree the solution is a bit hacky, but I guess there is nothing else we can do. Looks like the issue will not be prioritised by cypress team so I think this workaround is necessary for the moment.

Thanks for the help!

**Comment by sakalaca** [comment]
Hey @FFdhorkin after implementing of `deasync` library reporter stopped to work in our project. How did you overcome this issue (if you experienced it):

"cypress-testrail-reporter" reporter blew up with error:
Error: Could not locate the bindings file. Tried:
 → /Users/ATopcic/Documents/Project/r2-mono/e2e-tests-cypress/node_modules/deasync/build/deasync.node
 → /Users/ATopcic/Documents/Project/r2-mono/e2e-tests-cypress/node_modules/deasync/build/Debug/deasync.node
 → /Users/ATopcic/Documents/Project/r2-mono/e2e-tests-cypress/node_modules/deasync/build/Release/deasync.node
 → /Users/ATopcic/Documents/Project/r2-mono/e2e-tests-cypress/node_modules/deasync/out/Debug/deasync.node
 → /Users/ATopcic/Documents/Project/r2-mono/e2e-tests-cypress/node_modules/deasync/Debug/deasync.node
 → /Users/ATopcic/Documents/Project/r2-mono/e2e-tests-cypress/node_modules/deasync/out/Release/deasync.node
 → /Users/ATopcic/Documents/Project/r2-mono/e2e-tests-cypress/node_modules/deasync/Release/deasync.node
 → /Users/ATopcic/Documents/Project/r2-mono/e2e-tests-cypress/node_modules/deasync/build/default/deasync.node
 → /Users/ATopcic/Documents/Project/r2-mono/e2e-tests-cypress/node_modules/deasync/compiled/14.15.1/darwin/x64/deasync.node
 → /Users/ATopcic/Documents/Project/r2-mono/e2e-tests-cypress/node_modules/deasync/addon-build/release/install-root/deasync.node
 → /Users/ATopcic/Documents/Project/r2-mono/e2e-tests-cypress/node_modules/deasync/addon-build/debug/install-root/deasync.node
 → /Users/ATopcic/Documents/Project/r2-mono/e2e-tests-cypress/node_modules/deasync/addon-build/default/install-root/deasync.node
 → /Users/ATopcic/Documents/Project/r2-mono/e2e-tests-cypress/node_modules/deasync/lib/binding/node-v87-darwin-x64/deasync.node
    at bindings (/Users/ATopcic/Documents/Project/r2-mono/e2e-tests-cypress/node_modules/bindings/bindings.js:126:9)

I've tried to use different node versions but without success.

**Comment by FFdhorkin** [comment]
Unfortunately, I haven't seen that - I was unable to get the reporter to work **without** deasync.

This ticket recommends explicitly uninstalling and reinstalling deasync: https://github.com/abbr/deasync/issues/6

**Comment by sakalaca** [comment]
@FFdhorkin Unfortunately both solutions are not working in my case. I also notices that people are complaining that they can't use our reporter due the same issue. 

https://stackoverflow.com/questions/67420594/could-not-load-reporter-by-name-cypress-testrail-reporter
https://github.com/abbr/deasync/issues/142

Which node version are you using?

**Comment by mickosav** [comment]
@sakalaca Are you maybe using new Mac with M1 chip? I see deasync has some c code to actually make requests blocking, It's a guess but I'm assuming it's not compiled to work on new mac architecture...

**Comment by sansoucyuRC** [comment]
@mickosav running into the exact same problem on a Mac with i9 chip. Reverting to version 1.2.2 of the report allow me to bypass this error though I'm running into other problems where the reporter creates the run but never send the results (which appears to be what which is fixed in this merged ticket).

**Comment by sansoucyuRC** [comment]
If it can help in debugging, this clearly appears to be hardware related. I managed to run the exact same project on remote machines without any problem. It makes local debugging more troublesome but at least I now managed to make it work.

**Comment by serhatgemici** [comment]
So a day of trial & error and comments hopping led me here :)

Have you guys ever experienced this later on or maybe heard of a walkaround? 

I'm running into the same problem, Mac Pro Core Intel Core i7. 
Cypress @9.2.1
cypress-testrail-reporter @1.3.3

Here's the error I get: 

`Error: Could not locate the bindings file. Tried:
 → /Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/node_modules/deasync/build/deasync.node
 → /Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/node_modules/deasync/build/Debug/deasync.node
 → /Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/node_modules/deasync/build/Release/deasync.node
 → /Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/node_modules/deasync/out/Debug/deasync.node
 → /Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/node_modules/deasync/Debug/deasync.node
 → /Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/node_modules/deasync/out/Release/deasync.node
 → /Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/node_modules/deasync/Release/deasync.node
 → /Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/node_modules/deasync/build/default/deasync.node
 → /Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/node_modules/deasync/compiled/16.5.0/darwin/x64/deasync.node
 → /Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/node_modules/deasync/addon-build/release/install-root/deasync.node
 → /Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/node_modules/deasync/addon-build/debug/install-root/deasync.node
 → /Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/node_modules/deasync/addon-build/default/install-root/deasync.node
 → /Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/node_modules/deasync/lib/binding/node-v98-darwin-x64/deasync.node
    at bindings (/Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/node_modules/deasync/index.js:30:31)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.Module._load (/Users/serhat.gemici/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/lib/override_require.js:15:27)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/dist/testrail.js:52:15)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.Module._load (/Users/serhat.gemici/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/lib/override_require.js:15:27)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/dist/cypress-testrail-reporter.js:21:18)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.Module._load (/Users/serhat.gemici/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/lib/override_require.js:15:27)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/serhat.gemici/Desktop/Cypress Demo BDD  TR/node_modules/cypress-testrail-reporter/index.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.Module._load (/Users/serhat.gemici/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/lib/override_require.js:15:27)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Function.loadReporter (/Users/serhat.gemici/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:553:14)
    at ProjectBase.initializeReporter (/Users/serhat.gemici/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/lib/project-base.js:400:32)
    at ProjectBase.startWebsockets (/Users/serhat.gemici/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/lib/project-base.js:418:39)
    at ProjectBase.<anonymous> (/Users/serhat.gemici/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/packages/server/lib/project-base.js:167:18)
    at Generator.next (<anonymous>:null:null)
    at fulfilled (/Users/serhat.gemici/Library/Caches/Cypress/9.2.1/Cypress.app/Contents/Resources/app/node_modules/tslib/tslib.js:114:62)`
    
When I downgrade the cypress-testrail-reporter to v1.2.2, it doesn't get the "Could not locate the bindings file" error, but this time it never creates a test run:
(domain names& passwords starred)

`Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16) 
{
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80,
  config: {
    adapter: [Function: httpAdapter],
    transformRequest: { '0': [Function: transformRequest] },
    transformResponse: { '0': [Function: transformResponse] },
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.18.1',
      'Content-Length': 178
    },
    method: 'post',
    url: '*******/index.php?/api/v2/add_run/3',
    auth: {
      username: 'serhat.gemici@**********',
      password: '**********'
    },
    data: '{"suite_id":8,"name":"name Jan 12th 2022, 18:54 (+01:00)","description":"For the Cypress run visit https://dashboard.cypress.io/#/projects/runs","include_all":true,"case_ids":[]}'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      o  C2853 PLZ Modal
nwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'http:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '**********/index.php?/api/v2/add_run/3',
      method: 'post',
      headers: [Object],
      agent: undefined,
      auth: 'serhat.gemici@*********:**********',
      hostname: null,
      port: null,
      nativeProtocols: [Object],
      pathname: '*********/index.php',
      search: '?/api/v2/add_run/3'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 178,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST ********/index.php?/api/v2/add_run/3 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.18.1\r\n' +
        'Content-Length: 178\r\n' +
        'Host: localhost\r\n' +
        'Authorization: Basic *********' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '*********/index.php?/api/v2/add_run/3',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: '********/index.php?/api/v2/add_run/3',
    [Symbol(kCapture)]: false
  },
  **response: undefined**
}`

**Comment by tlei123** [comment]
@serhatgemici , you may wanna try Gleb Bahmutov's [cypress-testrail-simple](https://github.com/bahmutov/cypress-testrail-simple).  Gleb's former VP of Engineering at Cypress.  Good luck!  :)

**Comment by serhatgemici** [comment]
@tlei123 , I'm on it, thank you :)

**Pull request merged**
