### PR TITLE
Update reporter to be able to use with Cypress v10

### PR DESCRIPTION
**Pull request by sakalaca**
Due to the recent changes in Cypress v10, we must update validation function for counting the spec files to include also `cypress/e2e` path which is default one from now on. 

Additionally I updated README file to point out which folder structure is supported by reporter. 

@vivifyideas Who is responsible person for this repo, I remember that @mickosav was the main one before?

### CODE REVIEW

**Comment by sakalaca** [comment]
@vivifyideas Anyone who can review and merge this one???

**Comment by sakalaca** [comment]
@milosh012 Hi, can we also raise a version of reporter to 1.3.4 since we just merged those changes but we can't actually see them after installing the library?

**Comment by milosh012** [comment]
sure, I will bump the version too. I will let you know when its done

**Comment by sakalaca** [comment]
Awesome, thanks a lot.

**Comment by milosh012** [comment]
@sakalaca version updated!

**Comment by sakalaca** [comment]
@milosh012 Awesome, thanks a lot.

**Pull request merged**
