### PR TITLE
Updated get_cases api call & packages

### PR DESCRIPTION
**Pull request by sakalaca**
@mickosav Can you review/merge this one? Recently TestRail changed response of the get_cases api call which breaks our reporter (I believe everyone is having the same issue atm), so this PR should fix that. 

https://www.gurock.com/testrail/docs/api/reference/cases#getcases

image

### CODE REVIEW

**Comment by adodge1** [comment]
@mickosav ! yes this fix is needed. thank you @sakalaca

**Comment by sakalaca** [comment]
@mickosav Any news on this one?

**Comment by mickosav** [comment]
Sorry, I somehow completely missed this PR. Merging now...

**Comment by adodge1** [comment]
@sakalaca  your changes looked great until I saw that the version before this had removed dasync because this dasync is breaking the reporter. Is there a way to add the changes we need for the map.cases without adding dasync back? see thsi pull request by @mncharlton 
https://github.com/Vivify-Ideas/cypress-testrail-reporter/pull/25

**Comment by mickosav** [comment]
@adodge1 If my memory serves me correct, the main reason deasync was added was because cypress was terminating reporter process too early and we couldn't publish results reliably (depending on how long your test take).

Deasync has one fairly simple C++ script which blocks execution (exactly what we needed at the time). Drawback is, it's not maintained regularly so I'm guessing you might encounter some errors if it's not supporting you arch or node version.

We had people with new Macs on M1 chips that were saying they have `deasync` errors on their machine, but their tests were passing on CI...

If you have a solution, well tested PR would be welcome!

It's more important to us that test are run and reported reliably on CI than on local machine, so keep that in mind.

**Comment by adodge1** [comment]
@mickosav  sounds good . Thanks

**Comment by sakalaca** [comment]
@adodge1 I completely agree what @mickosav said, it was implemented in this PR: https://github.com/Vivify-Ideas/cypress-testrail-reporter/pull/16 and we have it since v1.2.4, so this PR didn't do anything regarding that. Also for me it doesn't work from local but in CI it works perfectly.

**Comment by sakalaca** [comment]
@AnumGee Yes, this was change made by TestRail update and you have to use latest version of our reporter 1.3.3

**Pull request merged**
